from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional, Set, Union, Callable, Iterable
from dataclasses import dataclass, field
from pydantic import ValidationError as pyValErr
from enum import Enum
import pandas as pd
import numpy as np
import logging
from pathlib import Path


class ValidationError(ValueError):
    def __init__(
        self,
        *,
        errors: Iterable[str] | None = None,
        expected_type: object = dict[str, list[str]],
        possible_keys: Iterable[str] | None = None,
        base_msg: str = "",
    ):
        self.errors = list(errors or [])
        self.expected_type = expected_type
        self.possible_keys = list(possible_keys or [])
        self.base_msg = base_msg

        super().__init__(self._format_message())

    def add(self, msg: str) -> None:
        """Add a single validation error."""
        self.errors.append(msg)

    def extend(self, msgs: Iterable[str]) -> None:
        """Add multiple validation errors."""
        self.errors.extend(msgs)
    
    def format_pydantic_error(self, err: pyValErr) -> str:
        errors = err.errors()
        type_name = err.title
        lines = [f" - {len(errors)} validation errors in expected type: {type_name}"]
        
        for e in errors:
            # Location like ('also_bad', 1) → "also_bad.1"
            loc = ".".join(str(part) for part in e.get("loc", ()))
            val = e.get("input", "<unknown>")
            actual_type = type(val).__name__
            expected_type = e.get("type", "unknown_type")

            lines.append(f"  - key: {loc} ")
            lines.append(f"\texpected {expected_type}, got value `{val}` of type {actual_type}")
        
        return "\n".join(lines)
    
    def reraise_pydantic(self, err):
        self.add(self.format_pydantic_error(err))
        raise self

    def _format_message(self) -> str:
        parts = [f"{self.base_msg}:"] if self.base_msg else []

        if self.errors:
            parts.append("  Details:")
            for err in self.errors:
                parts.append(f"{err}")

        if self.expected_type is not None:
            parts.append(f"\n  Expected type: {self.expected_type}")

        if self.possible_keys:
            parts.append(f"  Possible keys: {self.possible_keys}")

        return "\n".join(parts)

    def __str__(self) -> str:
        # ensures message always reflects current state if mutated
        return self._format_message()




class DataType(Enum):
    """Enumeration of supported data types for validation."""
    DATAFRAME = "pandas.DataFrame"
    NUMPY_ARRAY = "numpy.ndarray"
    LIST = "list"
    DICT = "dict"
    STRING = "str"
    INTEGER = "int"
    FLOAT = "float"
    BOOLEAN = "bool"
    PATH = "pathlib.Path"


class DataSource(Enum):
    """Enumeration of data source types."""
    EXTERNAL = "external"  # Provided by input data (e.g., images, labels from file)
    PIPELINE = "pipeline"  # Generated by previous pipeline stages


@dataclass
class DataRequirement:
    """Specification for a data dependency."""
    key: str
    data_type: DataType
    source: DataSource
    required: bool = True
    description: str = ""
    shape_constraint: Optional[Callable] = None
    value_constraint: Optional[Callable] = None
    
    def validate(self, data: Dict[str, Any]) -> tuple[bool, str]:
        """Validate that the requirement is satisfied by the data."""
        if self.key not in data:
            if self.required:
                return False, f"Required key '{self.key}' missing from data"
            return True, ""
        
        value = data[self.key]
        
        # Type validation
        if self.data_type == DataType.DATAFRAME and not isinstance(value, pd.DataFrame):
            return False, f"Key '{self.key}' must be pandas DataFrame, got {type(value)}"
        elif self.data_type == DataType.NUMPY_ARRAY and not isinstance(value, np.ndarray):
            return False, f"Key '{self.key}' must be numpy array, got {type(value)}"
        elif self.data_type == DataType.LIST and not isinstance(value, list):
            return False, f"Key '{self.key}' must be list, got {type(value)}"
        elif self.data_type == DataType.DICT and not isinstance(value, dict):
            return False, f"Key '{self.key}' must be dict, got {type(value)}"
        elif self.data_type == DataType.STRING and not isinstance(value, str):
            return False, f"Key '{self.key}' must be string, got {type(value)}"
        elif self.data_type == DataType.INTEGER and not isinstance(value, int):
            return False, f"Key '{self.key}' must be integer, got {type(value)}"
        elif self.data_type == DataType.FLOAT and not isinstance(value, (int, float)):
            return False, f"Key '{self.key}' must be float, got {type(value)}"
        elif self.data_type == DataType.BOOLEAN and not isinstance(value, bool):
            return False, f"Key '{self.key}' must be boolean, got {type(value)}"
        elif self.data_type == DataType.PATH and not isinstance(value, (str, Path)):
            return False, f"Key '{self.key}' must be path-like, got {type(value)}"
        
        # Shape constraint validation
        if self.shape_constraint and hasattr(value, 'shape'):
            if not self.shape_constraint(value.shape):
                return False, f"Key '{self.key}' failed shape constraint"
        
        # Value constraint validation  
        if self.value_constraint and not self.value_constraint(value):
            return False, f"Key '{self.key}' failed value constraint"
        
        return True, ""




@dataclass 
class ConfigRequirement:
    """Specification for a configuration parameter.

        Thinking thru cases, generally
            1) key not in default params  (this can be b/c hasn't been spec'd or user input error)
            2) key is required
            3) value type is invalid
            4) 

        notes:
            - need to differentiate between config req's and params that come from example metadata (such as coloc params)
    """
    key: str
    data_type: DataType
    required: bool = True
    default_value: Any = None
    description: str = ""
    validator: Optional[Callable] = None
    
    def extract(self, config: Dict[str, Any]) -> Any:
        """Extract and validate configuration value."""
        if self.key not in config:
            if self.required and self.default_value is None:
                raise ValueError(f"Required config key '{self.key}' missing")
            return self.default_value
        
        value = config[self.key]
        
        # Apply validator if provided
        if self.validator and not self.validator(value):
            raise ValueError(f"Config key '{self.key}' failed validation")
        
        return value