# -*- coding: utf-8 -*-
"""
Core implementation of data management structure

## Components
- Example
    - represents directory containing all data related to/generated from a single source (e.g. a raw microscope image)
    - 'all data' here includes:
        - source image
        - segmentation of various objects (e.g. synapses, dendrites, cell bodies, etc.)
        - ROIs (areas to include in certain analyses)
        - spaital maps (atlas registrations)
    - identified by metadata.yml file containing info about data sources/formats, segmentation parameters, etc.
- Project
    - represents a collection of 'examples' and analysis done on this data
    - directory structure and contents
        - examples: example instances, as described above
        - __config__: configuration files of parameters used to generate segmentation, quantification, analysis, etc.
        - __logs__: log files generated during running of pipeline elements (seg, quant, etc.)
        - outputs: data derived during quantification/analysis runs (e.g. object counts/properties) 
            - each folder in outputs represents analysis done with a specfic set of parameters.
                this is done to compare results generated by different param values, organize different types of analyses,
                as well helping clarify what parameters were used to generate the data.
                This containins things like tables of individual and aggregated synapse properties 

## notes
- instantiation
    - a project and all it's examples are meant to be generated together during a segmentation run 


"""
from __future__ import annotations
from typing import List, Dict, Tuple, Optional, Iterable, TYPE_CHECKING, Any
from copy import deepcopy
from math import e
import os
import sys
import numpy as np
from pathlib import Path
import functools
import re
import pprint
import pandas as pd
from tabulate import tabulate
import yaml


from SynAPSeg.utils import utils_general as ug
from SynAPSeg.config import constants


if TYPE_CHECKING:
    from SynAPSeg.IO.metadata_handler import MetadataParser


def get_MetadataParser():
    """ help manage import, returns module """
    from SynAPSeg.IO.metadata_handler import MetadataParser
    return MetadataParser


class DataFormatValidator:
    """Utility class for validating and inferring data formats"""
    
    @staticmethod
    def infer_format_from_shape(shape: Tuple[int], base_shape_mapping: Dict[str, int]) -> str:
        """
        Infer axis format by matching dimensions to known base dimensions
        
        Args:
            shape: Tuple of dimensions from actual data
            base_shape_mapping: Dictionary mapping axis labels to their expected sizes
            
        Returns:
            String representing the inferred format (e.g., 'YXC')
        """
        available_axes = list(base_shape_mapping.items())
        inferred_format = ''
        
        for dimension in shape:
            found_match = False
            for axis, size in available_axes:
                if dimension == size:
                    inferred_format += axis
                    available_axes.remove((axis, size))
                    found_match = True
                    break
            
            if not found_match:
                raise ValueError(f"Could not match dimension {dimension} to any available axis")
        
        return inferred_format
    
    @staticmethod
    def validate_shape_format_consistency(
        shape: Tuple[int], 
        format_str: str, 
        base_shape_mapping: Dict[str, int]
    ) -> dict:
        """
        Validate that a shape and format string are consistent
        
        Returns:
            Dictionary with validation results
        """
        # Build axis-to-shape mapping from format string
        axis_shape_mapping = {}
        for i, axis in enumerate(format_str):
            if i >= len(shape):
                return {'length_match': False, 'shape_consistency': False}
            axis_shape_mapping[axis] = shape[i]
        
        # Rebuild shape from format
        rebuilt_shape = [axis_shape_mapping[axis] for axis in format_str]
        
        return {
            'length_match': len(format_str) == len(shape),
            'shape_consistency': list(shape) == rebuilt_shape,
            'axis_mapping': axis_shape_mapping,
        }





class Example:
    """ directory containing image data """

    def __init__(self, path_to_example:str, make:bool=False):
        self.path_to_example = path_to_example
        self.name: str = Path(self.path_to_example).name
        self.exmd = {}
        self.project_name = Path(self.path_to_example).parts[-3]

        self.initialize_example(make=make)
    
    def initialize_example(self, make=False):
        if not make: assert os.path.exists(self.path_to_example)
        ug.verify_outputdir(self.path_to_example, makedirs=make)
        self.exmd = self.get_metadata_parser().try_get_metadata(self.path_to_example, FILE_MAP=None, silent=True)
        self.is_complete = self.check_marked_complete(self.path_to_example)
        self.is_skipped = self.check_marked_skip(self.path_to_example)
    
    @staticmethod
    def is_ex_dir(path_to_example):
        """check if path is an example directory by looking if it contains metadata.yml file"""
        if not os.path.isdir(path_to_example):
            return False    
        if not "metadata.yml" in os.listdir(path_to_example):
            return False
        return True
    
    @staticmethod
    def check_marked_complete(path_to_example):
        """check if an example directory is complete by looking if it contains a 'complete.txt' file"""
        IS_COMPLETE = True if 'complete.txt' in os.listdir(path_to_example) else False
        return IS_COMPLETE
    
    @staticmethod
    def check_marked_skip(path_to_example):
        """check if an example directory is complete by looking if it contains a 'complete.txt' file"""
        IS_SKIP = True if "__skip_this_example.txt" in os.listdir(path_to_example) else False
        return IS_SKIP
    
    def set_logger(self, logger):
        self.logger = logger
    
    def get_metadata_parser(self) -> type['MetadataParser']:
        """ returns metadata parser class - exists to centralize and avoid import conflicts """
        return get_MetadataParser()
    
    def log(self, msg, lvl='info'):
        if hasattr(self, "logger"):
            getattr(self.logger, lvl)(msg)

    def get_image_path(self):
        """ get the path of the examples source image """
        img_path = self.exmd.get('image_path', self.exmd.get('czi_path'))
        return img_path
    
    def get_path(self, fn:str) -> str:
        """ return the full path to a filename, if present else Raise error """
        p = os.path.join(self.path_to_example, fn)
        if not os.path.exists(p):
            raise FileNotFoundError(f"{fn} not found in example: {self.name}")
        return p
        

    def unmark_complete(self) -> None:
        """ deletes complete.txt from the example dir """
        cpath = os.path.join(self.path_to_example, 'complete.txt')
        if os.path.exists(cpath):
            os.remove(cpath)
        
    def mark_complete(self) -> None:
        """
        Marks the example as complete, for instance by writing a 'complete.txt' file in the example directory.
        """
        try:
            complete_filepath = os.path.join(self.path_to_example, "complete.txt")
            with open(complete_filepath, "w") as f:
                f.write("Processing complete.")
            self.log(f"Marked complete at {complete_filepath}.")
            
        except Exception as e:
            self.log(f"Error marking complete: {e}", lvl='error')
            raise
    
    def write_metadata(self) -> None:
        """ write the current example.exmd (metadata) to disk, overwrites existing version """
        self.get_metadata_parser().write_metadata(self.path_to_example, self.exmd)
    
    def write_data(self, data, filename, fmt, tiff_metadata=None, OUTPUT_IMAGE_PYRAMID=False):
        """ 
        write additional data associated with this example to disk - ensures proper metadata handling and formating
        
        Args:
            data: np.ndarray (TODO expand to other data types)
            write_array args
                filename, fmt, tiff_metadata=None, OUTPUT_IMAGE_PYRAMID=False
        """
        self.get_metadata_parser().write_data_to_example(
            self, 
            data, filename, fmt, 
            tiff_metadata=tiff_metadata, OUTPUT_IMAGE_PYRAMID=OUTPUT_IMAGE_PYRAMID
        )
    
    def __str__(self, exclude_keys=None):
        if exclude_keys is None:
            exclude_keys = ['image_metadata', 'model_training_config', 'segmentation_pipeline_config', 'output_dir']
        assert isinstance(exclude_keys, list)
        assert isinstance(self.exmd, dict)

        concise_exmd = {k:v for k,v in self.exmd.items() if not(k in exclude_keys)}
        return pprint.pformat(concise_exmd)
    
    def __repr__(self):
        return f"Example(name=\'{self.name}\', project_name=\'{self.project_name}\')"

    
    def get_filenames(
            self, 
            pattern: str = r'.*\..*',
            excluded_files: Optional[List[str]] = None,
            fail_on_empty=True,
            warn=True,
        ) -> list[str]:
        """
        Get list of files present in the example directory that match the pattern provided
        
        Args:
            pattern: used for re.match, defaults to grabbing all files
                e.g. '(?i)\\.tiff?\\Z' <-- example to match str ending with .tif or .tiff & is case-insensitive
            excluded_files: List of files to exclude, should be formated as filename with suffix
                e.g. ['ROI_0.tiff']
            fail_on_empty: raises error if not found
            warn: print warning if not found and not fail_on_empty
            
        Returns:
            List of filenames found in the example directory
        """
        if excluded_files is None:
            excluded_files = []

        files = ug.get_contents(self.path_to_example, filter_str=pattern, pattern=True, fail_on_empty=fail_on_empty, warn=warn)
        files = [Path(fp).name for fp in files if Path(fp).name not in excluded_files]
        return files
    
    def check_example_filenames(self, required_filenames:list) -> tuple[bool, list]:
        """ 
        Check if all required filenames are in an examples contents

        Args:
            required_filenames: list of filenames or list[list[str]] to check if any of inner list is present
        Returns:
            whether check passed
            list of filenames that failed check    
        """
        ex_dir_contents = self.get_filenames(pattern='.*')
        matches, errors = [], []
        for req_fn in required_filenames:
            if len(req_fn) == 0: # skip empty lists/strings
                continue 
            elif isinstance(req_fn, str):
                passed = req_fn in ex_dir_contents
            elif isinstance(req_fn, list):
                passed = ug.any_isin(ex_dir_contents, req_fn)
            else:
                raise ValueError(f"required_filenames elements must be either string or list but got: {req_fn}")
            
            matches.append(passed)
            if not passed:
                errors.append(req_fn)

        return all(matches), errors
    
    def get_annotations(self, ex_contents=None, ann_fn_prefixes=['annotated_', 'ROI_']):
        """ 
            get list of annotated filenames in an examples directory 

            Args:
                ann_fn_prefixes (List[str]): filenames that start with any of these strings are considered annotations
        """
        ex_contents = ex_contents or self.get_filenames()
        ann_fns = [c for c in ex_contents if any([c.startswith(pre) for pre in ann_fn_prefixes])]
        return ann_fns
        
    def has_data(self, data_key:str):
        """ 
        returns true if the key points to a filename that exists in the example 
            TODO only supports keys with filenames sans suffix, future should support if suffix is included
        """
        return self._prefix_in_ex_files(data_key)
    
    def _prefix_in_ex_files(self, data_key:str):
            return data_key in [ug.get_prefix(el) for el in self.get_filenames()]
        
    def get_base_shape_mapping(self, raw_img_format='STCZYX') -> Dict[str, int]:
        """
        Extract base shape mapping from existing metadata
        
        Args:
            raw_img_format: shape format of raw_img.tiff, e.g. 'STCZYX'

        Returns:
            Dictionary mapping axis labels to their sizes
        """
        base_shape = self.exmd['data_metadata']['data_shapes']['raw_img']
        assert len(base_shape) == len(raw_img_format), f"lengths do not match. base_shape:{base_shape}, raw_img_format:{raw_img_format}"
        return dict(zip(raw_img_format, base_shape))
    

    def get_clcdb(
            self,
            conf_key=None,
            conf_path=None,
            default_params_path=None,
            colocalizations=None,
        ):
        """ 
        fetch or make ImgDB colocalization information 

        Args:
            colocalizations (list[list[int,...]])- optional, make imgdb from supplied colocs
            conf_path (str) - optional, path to quantification config .yaml file. defaults to constants.QUANT_CONFIG_PATH
            conf_key (str) - optional, key in quant config. defaults to self.project_name
        """
        from SynAPSeg.IO.BaseConfig import BaseConfig, read_config
        from SynAPSeg.utils.utils_ImgDB import ImgDB
        from SynAPSeg.IO.metadata_handler import MetadataParser

        conf_key = conf_key or self.project_name
        conf_path = conf_path or constants.QUANT_CONFIG_PATH
        default_params_path = default_params_path or constants.QUANT_DEFAULT_PARAMETERS_PATH

        if colocalizations is None: # try to load from quant config
            
            qparams = BaseConfig(conf_key, conf_path, default_params_path)
            
            coloc_stage_name = 'colocalization'
            if 'colocalization' not in qparams['STAGE_PARAMS'].keys():
                raise ValueError('config file does not have a colocalization stage associated.')
            
            # colocalizations = qparams['COLOCALIZATIONS'] # old format
            colocalizations = qparams['STAGE_PARAMS']['colocalization']['COLOCALIZATIONS'] # new format
                           

        self.exmd.update({'COLOCALIZE_PARAMS':{"colocalizations":colocalizations}})
        image_channels, clc_nuc_info = MetadataParser.get_imgdb_colocal_nuclei_info(self.exmd)
        imgdb = ImgDB(image_channels=image_channels, colocal_nuclei_info=clc_nuc_info)
        return imgdb
    
    
    def analyze_file_shapes_and_formats(self, tiff_files: List[str], raw_img_format: str ='STCZYX') -> Dict:
        """
        Analyze shapes and infer formats for TIFF files
        
        Args:
            tiff_files: List of TIFF filenames to analyze
            raw_img_format: string representation of shape format for raw_img.tiff
            
        Returns:
            Dictionary with shape and format information
        """
        from SynAPSeg.utils.utils_image_processing import get_tiff_shape
        base_shape_mapping = self.get_base_shape_mapping(raw_img_format=raw_img_format)
        
        file_analysis = {
            'shapes': {},
            'inferred_formats': {},
            'validation_results': {}
        }
        
        for filename in tiff_files:
            file_path = os.path.join(self.path_to_example, filename)
            stem_name = Path(filename).stem
            
            # Get actual shape
            actual_shape = get_tiff_shape(file_path)
            file_analysis['shapes'][stem_name] = actual_shape
            
            # Infer format or get format if known
            try:
                known_format = self.exmd['data_metadata']['data_formats'][stem_name]
            except:
                known_format = None

            try:
                if not known_format:
                    inferred_format = DataFormatValidator.infer_format_from_shape(
                        actual_shape, base_shape_mapping
                    )
                else:
                    inferred_format = known_format
                file_analysis['inferred_formats'][stem_name] = inferred_format
                
                # Validate consistency
                validation = DataFormatValidator.validate_shape_format_consistency(
                    actual_shape, inferred_format, base_shape_mapping
                )
                file_analysis['validation_results'][stem_name] = validation
                
            except ValueError as e:
                file_analysis['inferred_formats'][stem_name] = None
                file_analysis['validation_results'][stem_name] = {
                    'error': str(e),
                    'length_match': False,
                    'shape_consistency': False
                }
        
        return file_analysis
    
    def validate_and_update_data_formats(
            self, 
            raw_img_format=None,
            required_files: Optional[List[str]] = None,
            excluded_files: Optional[List[str]] = ['thumbnail.tiff'],
        ) -> Dict:
        """
        Validate and update data format metadata for this example
        
        Args:
            required_files: List of files that must be present
            excluded_files: List of files to exclude from validation
            
        Returns:
            Dictionary with validation results and updated metadata
        """
        from SynAPSeg.utils.utils_image_processing import get_tiff_shape
        # TODO this checking for req'd files should be broken into different function
        if not required_files:
            required_files = []
        if excluded_files is None:
            excluded_files = []

        assert isinstance(required_files, list), f"required_files must be type list but got type: {type(required_files)}"
        assert isinstance(excluded_files, list), f"excluded_files must be type list but got type: {type(excluded_files)}"
        if 'thumbnail.tiff' not in excluded_files:
            excluded_files.append('thumbnail.tiff')
                
        # Get TIFF files
        tiff_files = self.get_filenames(pattern=r'\.tiff$', excluded_files=excluded_files)
        
        # Check required files are present
        missing_files = [f for f in required_files if f not in tiff_files]
        if missing_files:
            return {
                'validation_passed': False,
                'error': f"Missing required files: {missing_files}",
                'updated_metadata': None
            }
        
        # ensure metadata has proper keys
        for k in ['data_shapes', 'data_formats']:
            if k not in self.exmd['data_metadata']:
                self.exmd['data_metadata'][k] = {}

        # get raw_data_format from metadata if present in exmd and was not specified
        if raw_img_format is None:
            raw_img_format = self.exmd.get('current_format', 'STCZYX')
            raw_img_path = os.path.join(self.path_to_example, 'raw_img.tiff')
            if os.path.exists(raw_img_path):
                raw_img_shape = get_tiff_shape(raw_img_path)
                raw_img_format = raw_img_format[-len(raw_img_shape):]


        # Analyze shapes and formats
        analysis = self.analyze_file_shapes_and_formats(tiff_files, raw_img_format=raw_img_format)
        
        # Check if all validations passed
        all_validations_passed = all(
            result.get('length_match', False) and result.get('shape_consistency', False)
            for result in analysis['validation_results'].values()
            if 'error' not in result
        )
        
        if not all_validations_passed:
            failed_files = [
                filename for filename, result in analysis['validation_results'].items()
                if not (result.get('length_match', False) and result.get('shape_consistency', False))
            ]
            return {
                'validation_passed': False,
                'error': f"Validation failed for files: {failed_files}",
                'analysis': analysis,
                'updated_metadata': None
            }
        
        # Create updated metadata structure
        updated_metadata = {
            'data_shapes': analysis['shapes'],
            'data_formats': analysis['inferred_formats']
        }
        
        # Update the example's metadata
        self.exmd['data_metadata']['data_shapes'].update(updated_metadata['data_shapes'])
        self.exmd['data_metadata']['data_formats'].update(updated_metadata['data_formats'])
        
        return {
            'validation_passed': True,
            'analysis': analysis,
            'updated_metadata': updated_metadata
        }
    
    def get_px_scaling(self):
        """ 
        get the px scaling from own metadata, with backcompatibility 
        
        returns
            dict[str, float] - like {'X': 0.07059082892416223, 'Y': 0.07059082892416223, 'Z': 0.7699999999999998}
        """
        from ast import literal_eval
        
        scaling_raw = self.exmd['image_metadata'].get('scaling') 
        if scaling_raw:
            if isinstance(scaling_raw, str):
                return literal_eval(scaling_raw)
            elif isinstance(scaling_raw, dict):
                return scaling_raw
            else:
                raise ValueError(scaling_raw)
        return None
        
    # def update_image_scaling_metadata(self) -> bool:
    #     """
    #     Update image scaling metadata from the original image file
        
    #     Returns:
    #         True if successful, False otherwise
    #     """
    #     try:
    #         from SynAPSeg.IO.image_parser import ImageParser
    #         from utils import utils_czi
            
    #         # Get image path
    #         img_path = self.get_image_path()
    #         if not img_path or not os.path.exists(img_path):
    #             return False
            
    #         # Parse metadata from original image
    #         image_parser = ImageParser.create_parser(img_path, self.exmd)
    #         czi, scene_ids = utils_czi.read_czi(img_path)
    #         metadata = image_parser.extract_metadata(czi)
            
    #         # Update scaling information
    #         if 'scaling' in metadata:
    #             if 'image_metadata' not in self.exmd:
    #                 self.exmd['image_metadata'] = {}
    #             self.exmd['image_metadata']['scaling'] = metadata['scaling']
    #             self.exmd['__updated__'] = f"{ug.get_datetime()}"
    #             return True
            
    #         return False
            
    #     except Exception as e:
    #         print(f"Error updating scaling for {self.name}: {e}")
    #         return False
    

    def get_segmentation_results_path(self):
        """ returns the path to the init_segmentation_results file
                attempts to get .pdf version if available else the older .svg file is returned 
        """
        seg_res = self.get_filenames(pattern='init_segmentation_results')
        if len(seg_res) == 0:
            raise ValueError
        elif len(seg_res) == 1:
            seg_res_path = os.path.join(self.path_to_example, seg_res[0])
        else:
            seg_res_index = seg_res.index('init_segmentation_results.pdf')
            seg_res_path = os.path.join(self.path_to_example, seg_res[seg_res_index])
        return seg_res_path

    def get_segmentation_results(self, seg_res_path=None, dpi=300):
        """ load the segmentation results and convert to a numpy array"""    
        from SynAPSeg.utils.utils_image_processing import load_pdf, load_svg
        if seg_res_path is None:
            seg_res_path = self.get_segmentation_results_path()

        if seg_res_path.endswith('.pdf'):
            array = load_pdf(seg_res_path, 0, dpi)
        else:
            assert seg_res_path.endswith('.svg')
            array = load_svg(seg_res_path)
        return array


class Project:
    def __init__(
        self,
        project_path:                   str,
        examples_dir_name:              str = 'examples',
        outputs_dir_name:               str = 'outputs',
        make:                           bool = False
    ):
        
        # attributes 
        self.project_path:              Path = Path(project_path)
        self.name:                      str = self.project_path.name
        self.examples_dir_name:         str = examples_dir_name
        self.outputs_dir_name:          str = outputs_dir_name
        self.path_to_examples:          str | Path | None = None
        self.path_to_outputs:           str | Path | None = None
        self.logdir:                    str | Path | None = None
        self.configdir:                 str | Path | None = None
        self.logger:                    Any
        self.examples:                  List[Example] = []  # filled during self.set_examples if already exists
        self.excluded_examples:         List[Example] = [] # examples that have been filtered (proj.filter_examples) out will be stored here 
        self.name2ex:                   Dict[str, int] = {}
        self.example_names_are_unique:  bool | None = None
        
        # validate or make project path, project dirs, and if already exists, add examples
        self.initialize_project(make=make)
        
    def initialize_project(self, make=False):
        if not make and not os.path.exists(self.project_path): 
            raise ValueError(f"project does not exist at path:\n\t{self.project_path}")

        ug.verify_outputdir(self.project_path, makedirs=make)
        self.path_to_examples = ug.verify_outputdir(os.path.join(self.project_path, self.examples_dir_name))
        self.path_to_outputs =  os.path.join(self.project_path, self.outputs_dir_name)
        self.logdir =           ug.verify_outputdir(os.path.join(self.project_path, '__logs__'))
        self.configdir =        ug.verify_outputdir(os.path.join(self.project_path, '__config__'))
        
        if not make:
            self.set_examples(self.get_example_dirs())
        
    def set_examples(self, examples):
        self.name2ex = {}
        self.examples = examples
        example_names = [ex.name for ex in self.examples]
        self.example_names_are_unique = False

        try:
            assert len(set(example_names)) == len(example_names)
            self.name2ex = dict(zip(example_names, range(len(examples))))
            self.example_names_are_unique = True
        
        except AssertionError:
            print('warning example names not unique cannot look up examples by name must use indexing (e.g. proj.examples[9])')
            
    def setup_logger(
            self,         
            name: str, 
            log_filename: Optional[str] = None, 
            level='INFO'
        ) -> None: 
        """ set self.logger, writes to self.logdir, e.g. while running a pipeline """
        self.logger = self.get_metadata_parser().get_logger(name, self.logdir, log_filename, level)


    def get_example_dirs(self):
        """get paths to example directories given a root directory"""
        exdirs = ug.get_contents(self.path_to_examples, fail_on_empty=False, warn=False)
        if len(exdirs) == 0:
            print(f"Warning - project `{self.name}` - examples dir is empty")
            return []
        examples = [Example(el) for el in exdirs if Example.is_ex_dir(el)]
        return examples
    
    def get_output_dir(self, most_recent=True, name=None, idx=None):
        """ gets the path to the most recently created output direction, or if name is provided (TODO)"""
        OUTPUTS_BASE_DIR = ug.verify_outputdir(self.path_to_outputs)
        output_folders = ug.get_contents(OUTPUTS_BASE_DIR)

        if isinstance(name, str):
            output_dir = os.path.join(OUTPUTS_BASE_DIR, name)
        elif isinstance(idx, int):
            output_dir = output_folders[idx]
        elif most_recent:
            # Get most recent directory by creation time
            output_dir = max(output_folders, key=lambda x: os.path.getctime(x))
        else:
            raise ValueError (f"must provide an idx or name of output to get")

        assert os.path.exists(output_dir), f"could not find directory: {output_dir}"
        return output_dir

    def get_example(self, name: str) -> Example | None:
        """ 
        get an example by name e.g. '0000' 
            note: name='auto' is special case which returns result of self.get_next_example
        """
        if name.lower() == 'auto': 
            name = self.get_next_example()
            if name is None:
                return None

        if self.name2ex and self.example_names_are_unique:
            return self.examples[self.name2ex[name]]
        return None

    def get_next_example(self) -> Optional[str]:
        """ 
        handles get_example('auto') 

        returns 
            name of next available example by checking for first instance that is not completed and not marked skip 
            or None if none remain
        """
        
        for ex in self.examples:
            if (not ex.is_complete) and (not ex.is_skipped):
                return ex.name

        print('no examples to process were found.')
        return None 

    def get_metadata_parser(self) -> type['MetadataParser']:
        """ returns metadata parser class - exists to centralize and avoid import conflicts """
        return get_MetadataParser()
    
    def get_all_unique_filenames(self, pattern: str = r".*\\..*") -> set[str]:
        """ returns a set of all filenames found in each example directory """
        files = set()
        for ex in self.examples:
            for f in ex.get_filenames(pattern=pattern, fail_on_empty=False):
                files.add(f)
        return files
    

    def batch_attach_data(self, new_data_mds:list[dict], example_names: Optional[str | list[str]] = None) -> None:
        """ 
        Update metadata for several examples in a project, meant for attaching array format info to new data
            add datakey (filename without suffix), format, and shape (optional) to metadata.
                # TODO shape peek and ensure format matches existing array
            by default (example_names=None) applies to all examples
            only adds if the entry's key points to a file that exists in the example
        
        # TODO - protect adding formating - should do all the standard checks whenever format/shape is user-provided
        
        args:
            new_data_mds: - providing shape is optional if the filepath to added array data is found and parsed by uip.get_tiff_shape
                e.g. [{'key':'ROI_0', 'data_formats':'YX', 'data_shapes':[1908, 1908]}]
            example_names: 
                if not provided, applies to all examples in the project
                e.g. '0000' or ['0000', '0001', ...]
        """
        from SynAPSeg.utils.utils_image_processing import get_tiff_shape
        upd_keys = ['data_formats', 'data_shapes']

        example_names = None if not example_names else [example_names] if not isinstance(example_names, list) else example_names
        
        exmpls: list[Example]
        exmpls = self.examples if example_names is None else [self.get_example(name) for name in example_names]

        counter_update_sucesses = 0
        for ex in exmpls:
            _entry_success = 0
            for entry in new_data_mds:
                data_name = entry['key']

                for k in upd_keys:
                    if not ex.has_data(data_name): 
                        continue

                    # help get array shape if not provided
                    try:
                        shape = get_tiff_shape(ex.get_path(f"{data_name}.tiff"))
                    except:
                        shape = None
                    ex.exmd['data_metadata']['data_shapes'][data_name] = shape

                    if k in entry.keys():
                        ex.exmd['data_metadata'][k][data_name] = entry[k]
                        _entry_success += 1

            if _entry_success > 0:
                counter_update_sucesses+=1
                ex.write_metadata()
        
        if counter_update_sucesses < 1:
            raise KeyError(f"attempted metadata entry did not apply to any examples")
        
        print(f"succesfully updated metadata for {counter_update_sucesses}/{len(exmpls)} examples")


    def validate_all_examples_data_formats(
            self, 
            raw_img_format=None,
            required_files: Optional[List[str]] = None,
            excluded_files: Optional[List[str]] = None) -> Dict:
        """
        Validate data formats for all examples in the project
        
        Args:
            required_files: List of files that must be present
            excluded_files: List of files to exclude from validation
            
        Returns:
            Dictionary with validation results for all examples
        """
                  
        validation_results = {
            'passed_examples': [],
            'failed_examples': [],
            'validation_details': {},
            'overall_success': True
        }
        
        for example in self.examples:
            try:
                result = example.validate_and_update_data_formats(
                    raw_img_format=raw_img_format,
                    required_files=required_files,
                    excluded_files=excluded_files
                )
                
                validation_results['validation_details'][example.name] = result
                
                if result['validation_passed']:
                    validation_results['passed_examples'].append(example.name)
                else:
                    validation_results['failed_examples'].append(example.name)
                    validation_results['overall_success'] = False
                    
            except Exception as e:
                validation_results['failed_examples'].append(example.name)
                validation_results['validation_details'][example.name] = {
                    'error': str(e),
                    'validation_passed': False
                }
                validation_results['overall_success'] = False
        
        return validation_results
    
    def update_all_examples_scaling(self) -> Dict:
        """
        Update scaling metadata for all examples in the project
        
        Returns:
            Dictionary with update results
        """
        update_results = {
            'updated_examples': [],
            'failed_examples': [],
            'update_details': {}
        }
        
        for example in self.examples:
            try:
                success = example.update_image_scaling_metadata()
                update_results['update_details'][example.name] = {'success': success}
                
                if success:
                    update_results['updated_examples'].append(example.name)
                else:
                    update_results['failed_examples'].append(example.name)
                    
            except Exception as e:
                update_results['failed_examples'].append(example.name)
                update_results['update_details'][example.name] = {
                    'success': False,
                    'error': str(e)
                }
        
        return update_results
    
    def batch_update_metadata(
            self, 
            raw_img_format=None,
            required_files=None, 
            excluded_files=None,
            validate_formats: bool = True, 
            update_scaling: bool = False, 
            write_changes: bool = False
        ) -> Dict:
        """
        Batch update metadata for all examples
        
        Args:
            validate_formats: Whether to validate and update data formats
            update_scaling: Whether to update image scaling information
            write_changes: Whether to write changes to disk
            
        Returns:
            Dictionary with comprehensive results
        """
        results = {
            'format_validation': None,
            'scaling_updates': None,
            'write_results': None,
            'overall_success': True
        }
        
        if validate_formats:
            print("Validating data formats...")
            results['format_validation'] = self.validate_all_examples_data_formats(
                raw_img_format=raw_img_format,
                required_files=required_files, 
                excluded_files=excluded_files
            )
            if not results['format_validation']['overall_success']:
                results['overall_success'] = False
                print(f"Format validation failed for: {results['format_validation']['failed_examples']}")
        
        if update_scaling:
            print("Updating scaling metadata...")
            results['scaling_updates'] = self.update_all_examples_scaling()
            if results['scaling_updates']['failed_examples']:
                print(f"Scaling update failed for: {results['scaling_updates']['failed_examples']}")
        
        if write_changes and results['overall_success']:
            print("Writing metadata changes...")
            write_results = {'successful_writes': [], 'failed_writes': []}
            
            for example in self.examples:
                try:
                    self.get_metadata_parser().write_metadata(example.path_to_example, example.exmd)
                    write_results['successful_writes'].append(example.name)
                except Exception as e:
                    write_results['failed_writes'].append((example.name, str(e)))
            
            results['write_results'] = write_results
        elif write_changes and not results['overall_success']:
            print("Skipping write due to validation failures")
        
        return results

    @staticmethod
    def is_project_dir(project_path, examples_dir_name='examples', fail_silently=True):
        """ check if a directory is a project directory that contains data """
        try:
            MetadataParser = get_MetadataParser()
            path_to_examples_dir = os.path.join(project_path, examples_dir_name)
            example_dirs = os.listdir(path_to_examples_dir)
            conds = (
                os.path.exists(project_path), 
                os.path.exists(path_to_examples_dir),
                len(example_dirs) > 0,
                any([len(MetadataParser.try_get_metadata(os.path.join(path_to_examples_dir, exdir)))>0 for exdir in example_dirs]),
            )
            return all(conds)
        except Exception as e:
            if not fail_silently: 
                print(f'is_project_dir failed:\n{e}\n')
            return False
        
    @staticmethod
    def get_dir_progress(
        proj=None,
        FILE_MAP=None, 
        dir_examples=None, 
        ) -> tuple[pd.DataFrame, dict[str, list[Any]], int, int, int, dict[str, list[str]]]:
        """ 
        inspect and display overview of each example's status, src filename, and annotated files in a project 
        
        Args:
            - proj (optionally provide a project object) else must be None if passing path to dir to check through dir_examples
            - FILE_MAP (dict(str:list|str)) - only mark complete each value (list of possible filenames to look for, or str)
                note: if dict(str, list) is passed, if any fn in each list is found will return true to
                 allow for checking if one of several options is found.
                note: keys in filemap are ignored and only values are used for checking.
            - dir_examples (optional if project is provided) else must be path to examples directory
        returns:
            info_df, where_map, complete_count, has_annots, not_started_count, annotated_file_names
        """
        
        if not proj:
            assert isinstance(dir_examples, str) and os.path.exists(dir_examples)
            pth = Path(dir_examples)
            proj = Project(pth.parent, examples_dir_name=pth.stem)
        else:
            assert dir_examples is None
            dir_examples = proj.path_to_examples
        FILE_MAP = FILE_MAP or {}
        run_filemap_check = len(FILE_MAP)>0 # run check if not empty
        
        # collect example statuses
        where_map={'complete':[], 'skipped':[], 'has_annots':[], 'started':[], 'not_started':[]}
        complete_count=0
        skipped_count=0
        has_annots=0
        not_started_count=0

        # iter examples
        annotated_filenames_map = {}
        tab_table = []
        for example in proj.examples:
            assert isinstance(example, Example)
            
            amd = example.exmd.get('annotation_metadata', {})            
            if not isinstance(amd, dict): # e.g. 'notStarted'
                amd = {}
            ex_status = amd.get('status','')
            ex_notes = amd.get('notes','')
            ex_scenename = example.exmd.get('scene_name', '')
            
            # get anotated files in an examples dir
            contents = example.get_filenames(pattern='.*')
            ann_fns = example.get_annotations(ex_contents=contents) or []
            annotated_filenames_map[example.name] = ann_fns
            if len(ann_fns) > 0:
                where_map['has_annots'].append(example.path_to_example)
                has_annots+=1
            
            # check all files provided in the filemap exist in this examples directory
            if run_filemap_check:
                filemap_check_passed, filemap_check_errors = example.check_example_filenames(list(FILE_MAP.values()))
            else:
                filemap_check_passed, filemap_check_errors = None, []
            
            # track overall progress for this project
            if example.is_skipped:
                where_map['skipped'].append(example.path_to_example)
                skipped_count += 1
                ex_status += 'SKIP'
            elif example.is_complete and (filemap_check_passed is not False):
                where_map['complete'].append(example.path_to_example)
                complete_count += 1
                ex_status += 'COMPLETE'
            else:
                where_map['not_started'].append(example.path_to_example)
                not_started_count+=1

            # build display table 
            tab_vars = [example.name, ex_status, Path(example.get_image_path()).stem, ex_scenename, filemap_check_passed, filemap_check_errors, len(ann_fns), ann_fns, ex_notes]
            tab_table.append(tab_vars)

        print(proj.name)
        table_headers = ['ex_i', 'status', 'image_filename', 'scene_name', 'filemap_check', 'filemap_check_failures', 'annotated_count', 'annotated_filenames', 'notes']
        print(tabulate(tab_table, headers=table_headers, tablefmt="heavy_outline"))
        info_df = pd.DataFrame(tab_table, columns=table_headers)
        return  info_df, where_map, complete_count, has_annots, not_started_count, annotated_filenames_map
    
    def update_example_info(self, FILE_MAP: Optional[Dict]=None) -> None:
        """ 
        fetch example progress/info and write to project directory as example_info.csv 
            note: overwrites existing df 
        Args:
            FILEMAP: dict mapping 
        
        TODO:
            fix status=COMPLETE to auto set even if mapping not provide
        """
        progress = self.get_dir_progress(self, FILE_MAP)
        info_df = progress[0]
        outpath = os.path.join(self.project_path, 'example_info.csv')
        info_df.to_csv(outpath, index=False)

    def __str__(self):
        return ug.objdir(self, return_as_string=True)
    
    def __repr__(self):
        return str(self)
    
    def filter_examples(self, condition, **kwargs) -> None:
        """
        Updates self.examples with those that meet the given condition. 
            Those that do not meet condition will be added to self.excluded_examples
        
        Args:
            condition: A callable that takes an Example and returns True/False.
            kwargs: are passed to condition function
        
        Returns:
            None
        """
        exs = []
        exlc_exs = []
        for ex in self.examples:
            res = condition(ex, **kwargs)
            if res:
                exs.append(ex)
            else:
                exlc_exs.append(ex)
        self.set_examples(exs)
        self.excluded_examples.extend(exlc_exs)
    
    def reset_filtered_examples(self):
        self.set_examples(self.examples + self.excluded_examples) # TODO order is not preserved
        self.excluded_examples = []

    def filter_complete_examples(self):
        """ helper function to filter examples list so only those that have been marked complete and not marked as skip are present """
        cond = lambda ex: (ex.is_complete and (not ex.is_skipped))
        self.filter_examples(cond)
    
        
    def filter_example_contents(self, required_filenames, return_matches=False):
        """
        helper function to filter examples by whether they have required filenames

        Args:
            required_filenames: list(str | list) list of filenames to get
                strings should include filename and suffix (not full path)
                list elements represent analogous files that have different names e.g. ROI_0.tiff and ROI_0_ch0.tiff
                example:
                    required_filenames = ['mip_raw.tiff', ['ROI_0.tiff', 'ROI_0_edited.tiff'], 'ROI_1.tiff']
                    would get mip_raw, ROI_1, and either ROI_0 or, if not present, would look for ROI_0_edited
                
        """
        
        self.filter_examples(
            lambda ex: ex.check_example_filenames(required_filenames)[0]
        )

        if return_matches:
            ex_dict_matches = {}
            for ex in self.examples:
                ex_dir_contents = ex.get_filenames()
                matches = []
                for req_fn in required_filenames:
                    if isinstance(req_fn, str) and (req_fn in ex_dir_contents):
                        matches.append(req_fn)
                    elif isinstance(req_fn, list):
                        for _fn in req_fn:
                            if _fn in ex_dir_contents:
                                matches.append(_fn)
                                break
                ex_dict_matches[ex.name] = matches
            return ex_dict_matches

    def get_all_unique_filenames(
            self, 
            pattern: str = r'.*\..*', 
            examples: Iterable["Example"] | None = None,
        ) -> set[str]:
        """ returns a set of all filenames found in each example directory, if examples is None uses self.examples"""
        examples = examples or self.examples
        return set(ug.flatten_list([ex.get_filenames(pattern=pattern, fail_on_empty=False) for ex in examples]))
    

if bool(0):
    # compile index of examples with specific scaling values over several projects
    import ast
    ROOTDIR = r"R:\Confocal data archive\Pascal\SEGMENTATION_DATASETS"
    c = ug.get_contents(ROOTDIR)
    fetch={}
    fetch_sorted = {}
    fetch_counter = 0
    for pp in c[:]:
        try:
            proj = Project(pp)
        

            for ex in proj.examples:
                md = ex.exmd['image_metadata']
                zscale = ast.literal_eval(md['scaling'])['Z']
                # print(zscale)
                if zscale < 4e-07:
                    #get z slices
                    zscale*=1E6
                    zscale = round(zscale,3)
                    vals = {'zsize': zscale,'z':'None', 'chnames':list(ex.exmd['data_metadata']['channel_info'].values())}
                    try:
                       ifmt= md['init_image_format_target']
                       ishape = ast.literal_eval(md['shape'])
                       vals['fmt']=ifmt
                       vals['ishape']=ishape
                       vals['z']=ishape[(ifmt.upper().index('Z'))]
                       if len(ishape)==5 and len(ifmt)==6:
                           vals['z']=ishape[2]
                    except:pass
                    fetch[ex.path_to_example] = vals
                    fetch_sorted[f"{zscale}_{str(vals['z']).zfill(4)}_{fetch_counter}"] = ex.path_to_example
                    fetch_counter+=1
        except:
            continue

    import json
    with open('fetch_sorted.json','w') as f:
        json.dump(fetch_sorted, f)
    with open('fetch.json','w')as ff:
        json.dump(fetch, ff)
