#!/usr/bin/env python3
"""
This module aids with interpretation of results generated by the Classification pipeline
implements
    - ...
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, Sequence
import numpy as np
import pandas as pd


# —— Optional deps (guarded) ——
try:
    from sklearn.preprocessing import StandardScaler
    from sklearn.inspection import permutation_importance
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.pipeline import Pipeline as skPipeline
except Exception:
    StandardScaler = permutation_importance = RandomForestClassifier = skPipeline = None

try:
    from scipy import stats
except Exception:
    stats = None

try:
    from statsmodels.stats.multitest import multipletests
except Exception:
    multipletests = None


# # =========== Shared Schema (reuse from classification module) ===========
# @dataclass
# class DataSchema:
#     id_cols: List[str] = field(default_factory=list)
#     group_cols: List[str] = field(default_factory=list)
#     cat_cols: List[str] = field(default_factory=list)
#     num_cols: List[str] = field(default_factory=list)


# # =========== Registries ===========
# class _Registry:
#     def __init__(self): self._store: Dict[str, Any] = {}
#     def register(self, name: str):
#         def deco(cls):
#             self._store[name] = cls
#             return cls
#         return deco
#     def get(self, name: str):
#         if name not in self._store:
#             raise KeyError(f"Unknown component: {name}. Available: {list(self._store.keys())}")
#         return self._store[name]
#     def available(self) -> List[str]: return list(self._store.keys())


    

if __name__ == '__main__':
    # 1) After clustering
    result_df, meta_cls = pipeline.run(df)  # df has cluster_label

            